### Get JWT Token
@host = http://localhost:5263

POST {{host}}/api/Auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Pwd@12345"
}

### Call secure endpoint using JWT token
GET {{host}}/api/Users/secure-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJleHAiOjE3NDY3OTI5MTgsImlzcyI6Ik15TWljcm9zZXJ2aWNlc0NsZWFuQXJjaFBPQyIsImF1ZCI6Ik15TWljcm9zZXJ2aWNlc0NsZWFuQXJjaFBPQyJ9.MQm9B4yacHq1EjA3kN4TuVrY_rtW-pmsjTGx19GvwP0

### Create User
POST {{host}}/api/Users/Create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJleHAiOjE3NDY3OTI5MTgsImlzcyI6Ik15TWljcm9zZXJ2aWNlc0NsZWFuQXJjaFBPQyIsImF1ZCI6Ik15TWljcm9zZXJ2aWNlc0NsZWFuQXJjaFBPQyJ9.MQm9B4yacHq1EjA3kN4TuVrY_rtW-pmsjTGx19GvwP0

{
  "emailId": "reportingmanager@gmail.com",
  "userName": "ReportingManager"
}
